package jogodavelha;

/**
 *
 * @author adrian
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        inputPalavra = new javax.swing.JTextField();
        btnVerificarPalavra = new javax.swing.JButton();
        btnDica01 = new javax.swing.JButton();
        btnDica02 = new javax.swing.JButton();
        textoInformePalavra = new javax.swing.JLabel();
        forca = new javax.swing.JLabel();
        textoDaPalavraSorteada = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPalavraActionPerformed(evt);
            }
        });

        btnVerificarPalavra.setText("verificar");
        btnVerificarPalavra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerificarPalavraMouseClicked(evt);
            }
        });
        btnVerificarPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPalavraActionPerformed(evt);
            }
        });

        btnDica01.setText("Dica 01");
        btnDica01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDica01MouseEntered(evt);
            }
        });

        btnDica02.setText("Dica 02");
        btnDica02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDica02MouseEntered(evt);
            }
        });
        btnDica02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDica02KeyPressed(evt);
            }
        });

        textoInformePalavra.setText("INFORME A PALAVRA");

        forca.setIcon(new javax.swing.ImageIcon("C:\\Users\\adria\\Adrian\\Estudos\\Faculdade-SPI\\POO\\JogoDaForca\\src\\assets\\icons\\1-removebg-preview.png")); // NOI18N

        textoDaPalavraSorteada.setText("LETRAS DA PALAVRA SORTEADA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(textoInformePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputPalavra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerificarPalavra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(forca, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoDaPalavraSorteada, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(btnDica01)
                .addGap(18, 18, 18)
                .addComponent(btnDica02)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addComponent(forca, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(textoDaPalavraSorteada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(textoInformePalavra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificarPalavra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDica01)
                    .addComponent(btnDica02))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPalavraActionPerformed
        // TODO add your handling code here:
        System.out.println("Clicou");
    }//GEN-LAST:event_btnVerificarPalavraActionPerformed

    private void inputPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPalavraActionPerformed

    private void btnDica02KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDica02KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDica02KeyPressed

    private void btnVerificarPalavraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerificarPalavraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarPalavraMouseClicked

    private void btnDica01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDica01MouseEntered
        System.out.println("Dica 01");
    }//GEN-LAST:event_btnDica01MouseEntered

    private void btnDica02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDica02MouseEntered
        System.out.println("Dica 02");
    }//GEN-LAST:event_btnDica02MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDica01;
    private javax.swing.JButton btnDica02;
    private javax.swing.JButton btnVerificarPalavra;
    private javax.swing.JLabel forca;
    private javax.swing.JTextField inputPalavra;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel textoDaPalavraSorteada;
    private javax.swing.JLabel textoInformePalavra;
    // End of variables declaration//GEN-END:variables
}
